import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { MusicalNoteIcon } from "@heroicons/react/16/solid";
import { merriweather, merriweatherSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-100 ${merriweatherSans.className} font-[300]`}>
        <header>
          <Link
            href="/"
            className="p-4 font-[800] uppercase block text-xl flex w-full justify-center text-green-800"
          >
            <MusicalNoteIcon
              className={`w-6 h-6 inline-block mr-0.5 relative top-0.5`}
            />
            Tunes
          </Link>
        </header>
        <div className="flex px-4">{children}</div>
      </body>
    </html>
  );
}
